# Generated by Django 5.0.4 on 2024-04-24 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('sub_category_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('sub_category_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secondapp.category')),
            ],
        ),
    ]
