# Generated by Django 5.0.4 on 2024-04-24 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secondapp', '0003_remove_subcategory_category_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubCategory',
        ),
    ]
