# Generated by Django 5.0.4 on 2024-04-18 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='sub_category_id',
            field=models.IntegerField(auto_created=True, primary_key=True, serialize=False),
        ),
    ]
