# Generated by Django 5.0.4 on 2024-04-24 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_alter_subcategory_sub_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reason',
            fields=[
                ('reason_id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('reason', models.CharField(max_length=1000)),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.subcategory')),
            ],
        ),
    ]
