# Generated by Django 5.0.4 on 2024-04-24 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_reason'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
