# Generated by Django 5.0.4 on 2024-04-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0006_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='reason',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.DeleteModel(
            name='Reason',
        ),
    ]
