# Generated by Django 5.0.4 on 2024-04-24 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0007_subcategory_reason_delete_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='accept',
            field=models.BooleanField(default=False),
        ),
    ]
