# Generated by Django 5.0.4 on 2024-05-06 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0008_rename_user_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
