# Generated by Django 5.0.4 on 2024-05-02 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0009_alter_category_id_usertwofactorauthdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertwofactorauthdata',
            name='session_identifier',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
