# Generated by Django 5.0.4 on 2024-05-02 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0010_usertwofactorauthdata_session_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='category_id',
            new_name='category',
        ),
    ]
