# Generated by Django 5.0.4 on 2024-05-03 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0012_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertwofactorauthdata',
            old_name='user',
            new_name='username',
        ),
    ]
